// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flksjcridjsulhtemebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsa3NqY3JpZGpzdWxodGVtZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDg3ODIsImV4cCI6MjA3MjUyNDc4Mn0.zmrhBi_6D2Do0q6S2i1KCGfFqt9E6tfnmcy-OKHJUBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});